CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS hospitals (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, address text NOT NULL DEFAULT '', lat double precision NOT NULL DEFAULT 0, lng double precision NOT NULL DEFAULT 0, type text NOT NULL DEFAULT 'hospital', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, email text NOT NULL UNIQUE, password_hash text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS hospital_users (user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, hospital_id uuid NOT NULL REFERENCES hospitals(id) ON DELETE CASCADE, role text NOT NULL CHECK (role IN ('pharmacist','admin','network_admin')), PRIMARY KEY(user_id,hospital_id));
CREATE TABLE IF NOT EXISTS sessions (token text PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS skus (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), hospital_id uuid NOT NULL REFERENCES hospitals(id) ON DELETE CASCADE, name text NOT NULL, category text NOT NULL DEFAULT 'General', unit_cost numeric NOT NULL DEFAULT 0, cold_chain_required boolean NOT NULL DEFAULT false, default_daily_run_rate integer NOT NULL DEFAULT 5, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS inventory_batches (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), hospital_id uuid NOT NULL REFERENCES hospitals(id) ON DELETE CASCADE, sku_id uuid NOT NULL REFERENCES skus(id) ON DELETE CASCADE, batch_number text NOT NULL, quantity integer NOT NULL DEFAULT 0 CHECK(quantity >= 0), expiry_date date NOT NULL, unit_cost numeric NOT NULL CHECK(unit_cost >= 0), daily_run_rate integer NOT NULL DEFAULT 5 CHECK(daily_run_rate > 0), status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS stockout_requests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), hospital_id uuid NOT NULL REFERENCES hospitals(id) ON DELETE CASCADE, sku_id uuid NOT NULL REFERENCES skus(id) ON DELETE CASCADE, quantity_needed integer NOT NULL CHECK(quantity_needed > 0), urgency text NOT NULL DEFAULT 'routine' CHECK(urgency IN ('routine','urgent','emergency')), status text NOT NULL DEFAULT 'open' CHECK(status IN ('open','fulfilled','cancelled')), requested_by uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS transfers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), from_hospital_id uuid NOT NULL REFERENCES hospitals(id) ON DELETE CASCADE, to_hospital_id uuid NOT NULL REFERENCES hospitals(id) ON DELETE CASCADE, batch_id uuid REFERENCES inventory_batches(id) ON DELETE SET NULL, sku_id uuid NOT NULL REFERENCES skus(id) ON DELETE CASCADE, quantity integer NOT NULL CHECK(quantity > 0), status text NOT NULL DEFAULT 'suggested' CHECK(status IN ('suggested','pending','in_transit','completed','cancelled')), distance_km double precision NOT NULL DEFAULT 0, transfer_cost double precision NOT NULL DEFAULT 0, requested_by uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz);
CREATE TABLE IF NOT EXISTS notifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), hospital_id uuid NOT NULL REFERENCES hospitals(id) ON DELETE CASCADE, title text NOT NULL, message text NOT NULL, event_type text NOT NULL DEFAULT 'system', read_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS hospital_billing (hospital_id uuid PRIMARY KEY REFERENCES hospitals(id) ON DELETE CASCADE, plan text NOT NULL DEFAULT 'Starter', monthly_amount integer NOT NULL DEFAULT 0, status text NOT NULL DEFAULT 'active', updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS audit_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES users(id), hospital_id uuid REFERENCES hospitals(id), action text NOT NULL, entity_type text NOT NULL, entity_id uuid, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_v2_batches_hospital ON inventory_batches(hospital_id);
CREATE INDEX IF NOT EXISTS idx_v2_stockouts_hospital ON stockout_requests(hospital_id,status);
CREATE INDEX IF NOT EXISTS idx_v2_transfers_hospital ON transfers(from_hospital_id,to_hospital_id,status);
CREATE INDEX IF NOT EXISTS idx_v2_notifications_hospital ON notifications(hospital_id,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_v2_sessions_expiry ON sessions(expires_at);
